# Workflow name
name: Deploy Storybook

on:
  # Event for the workflow to run on
  push:
    branches: [main]
  # Izinkan manual trigger
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: bun install
          build_command: bun run build-storybook
          path: storybook-static 