# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    branches:
      - 'main' # Branch utama untuk deploy

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    # Job steps
    steps:
      # Manual Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Install Bun
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      # Build Library first
      - name: Build Library
        run: |
          bun install
          bun run build-lib
      
      #👇 Add Storybook build and deploy to GitHub Pages
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: bun install
          build_command: bun run build-storybook
          path: storybook-static
          checkout: false
      
      # Build Storybook
      - name: Build Storybook
        run: bun run build-storybook
      
      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 