# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    branches:
      - 'main' # Branch utama untuk deploy

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Job steps
    steps:
      # Manual Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Install Bun
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      # Install dependencies
      - name: Install dependencies
        run: bun install
      
      # Build Library
      - name: Build Library
        run: bun run build-lib
      
      # Build Storybook
      - name: Build Storybook
        run: bun run build-storybook
      
      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 